#30 - chore: Refactor build script for better code organization and readability

diff --git a/commands/web/woodoo_components/build b/commands/web/woodoo_components/build
--- a/commands/web/woodoo_components/build
+++ b/commands/web/woodoo_components/build
@@ -1,21 +1,25 @@
 #!/bin/bash
 #ddev-generated - Do not modify this file; your modifications will be overwritten.
 
+# Generates the Hyvä theme configuration
 function hyvaConfigGenerate() {
-    "${DDEV_COMPOSER_ROOT}"//bin/magento hyva:config:generate
+    "${DDEV_COMPOSER_ROOT}"/bin/magento hyva:config:generate
 }
 
+# Clears the Magento cache
 function clearCache() {
-    "${DDEV_COMPOSER_ROOT}"//bin/magento cache:flush
+    "${DDEV_COMPOSER_ROOT}"/bin/magento cache:flush
     echo -e "\n${txtgrn}Cache cleared${txtrst}"
 }
 
+# Clears the static files generated by Magento
 function clearStaticFiles() {
-    rm -rf "${DDEV_COMPOSER_ROOT}"/pub/static/*
-    rm -rf "${DDEV_COMPOSER_ROOT}"/var/view_preprocessed/*
-    echo -e "${txtgrn}Static files cleared${txtrst}"
+    rm -rf "${DDEV_COMPOSER_ROOT}"/pub/static/* "${DDEV_COMPOSER_ROOT}"/var/view_preprocessed/*
+    echo -e "${txtgrn}Magento Static files cleared${txtrst}"
 }
 
+# Builds the Magento theme specified by the first argument
+# This function checks for necessary dependencies like Node modules and Grunt, installs them if missing, and then runs Grunt tasks to build the theme.
 function buildMagentoDefault() {
     THEME_NAME=$1
     echo -e "${txtcyn}Start building ${txtpur}${THEME_NAME}${txtcyn} Theme ... please wait!\n${txtrst}"
@@ -28,39 +32,39 @@ function buildMagentoDefault() {
     fi
 
     # check if grunt exist
-    if [[ ! -f "${DDEV_COMPOSER_ROOT}/node_modules/.bin/grunt" ]]; then
+    if ! command -v grunt &> /dev/null; then
         echo -e "\n\n${txtcyn}${ICON_ERROR} Install missing Grunt${txtrst}\n\n"
 
         npm install grunt
         sudo npm install grunt -g
 
-        if [[ ! -f "${DDEV_COMPOSER_ROOT}/node_modules/.bin/grunt" ]]; then
-            echo -e "${txtcyn}${ICON_SUCCESS} Done. ${txtrst}"
+        if ! command -v grunt &> /dev/null; then
+            echo -e "${txtred}${ICON_ERROR} Could not install grunt. Please check your installation.${txtrst}"
         else
-            echo -e "${txtred}${ICON_ERROR} Could not install grunt. Please check ${DDEV_COMPOSER_ROOT}/node_modules/.bin/ ${txtrst}"
+            echo -e "${txtcyn}${ICON_SUCCESS} Grunt installed successfully.${txtrst}"
         fi
     fi
 
-    "${DDEV_COMPOSER_ROOT}"/node_modules/.bin/grunt clean
-    "${DDEV_COMPOSER_ROOT}"/node_modules/.bin/grunt less
+    runGruntTasks
 
-    # check if grunt task was successful
-    # trunk-ignore(shellcheck/SC2181)
+    # check if grunt tasks finished successfully
+    # This condition checks if the exit status of the previous command is equal to 0 (which means success) and then prints a success message.
+    # If the exit status is not 0, it tries to repair the issue by removing the node_modules directory and reinstalling the dependencies.
+    # After that, it runs the Grunt tasks again and checks the exit status again.
+
     if [[ $? -eq 0 ]]; then
         echo -e "${txtgrn}${ICON_SUCCESS} Grunt tasks finished${txtrst}\n\n"
         echo -e "\n${txtgrn}${ICON_SUCCESS}${bldcyn} Theme Build for ${txtpur}${THEME_NAME}${txtcyn} finished${txtrst}\n\n\n"
     else
         echo -e "\n\n${tsxtred}${ICON_ERROR} Grunt task failed. Try to repair it for you.${txtrst}\n\n"
-
         rm -rf "${DDEV_COMPOSER_ROOT}"/node_modules
         npm ci
 
-        "${DDEV_COMPOSER_ROOT}"/node_modules/.bin/grunt clean
-        "${DDEV_COMPOSER_ROOT}"/node_modules/.bin/grunt less
+        runGruntTasks
 
-        # trunk-ignore(shellcheck/SC2181)
+        # check again if grunt tasks finished successfully
         if [[ $? -eq 0 ]]; then
-            echo -e "${txtgrn}${ICON_SUCCESS} Grunt tasks finished${txtrst}\n\n"
+            echo -e "${txtgrn}${ICON_SUCCESS} Grunt tasks successfull!${txtrst}\n\n"
             echo -e "\n${txtgrn}${ICON_SUCCESS}${bldcyn} Theme Build for ${txtpur}${THEME_NAME}${txtcyn} finished${txtrst}\n\n\n"
         else
             echo -e "\n\n${bakred}\n\n  ${ICON_ERROR} Grunt task failed again. Could not repair.\n${txtrst}\n\n"
@@ -68,6 +72,11 @@ function buildMagentoDefault() {
             echo -e "\n${txtgrn}${ICON_ERROR}${bldcyn} Theme Build for ${txtpur}${THEME_NAME}${txtcyn} failed.${txtrst}\n\n"
         fi
     fi
+}
+
+function runGruntTasks() {
+    "${DDEV_COMPOSER_ROOT}"/node_modules/.bin/grunt clean
+    "${DDEV_COMPOSER_ROOT}"/node_modules/.bin/grunt less
 }
 
 function buildHyva() {
@@ -168,7 +177,7 @@ if [[ $1 == "build" && $2 == "" || $1 == "b" && $2 == "" || $1 == "build" && $2 
 fi
 
 # Build a specific Theme
-if [[ $1 == "build" && $2 != "" && $2 != "-f" || $1 == "b" && $2 != "" && $2 != "-f" ]]; then
+if [[ ($1 == "build" || $1 == "b") && $2 != "" && $2 != "-f" ]]; then
 
     # Check get all themes from config-themes.yaml
     checkThemePathExists
